// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://pvrqcuinoerspbdflxiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2cnFjdWlub2Vyc3BiZGZseGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwNjMwNzksImV4cCI6MjA4MDYzOTA3OX0.2Nf3nXm1KpXEUVmH4XfWT7N90-CTGTZPtbqfSh0ZcBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const REST_TIMEOUT_MS = 20_000;
// Auth can involve DB work (rate limits, password hashing, etc.). Allow a longer window than REST reads.
const AUTH_TIMEOUT_MS = 45_000;

const fetchWithTimeout: typeof fetch = async (input, init) => {
  // If a signal is already provided, respect it.
  if (init?.signal) return fetch(input, init);

  const url = typeof input === "string" ? input : (input as Request).url;
  const timeoutMs = url.includes("/auth/v1") ? AUTH_TIMEOUT_MS : REST_TIMEOUT_MS;

  const controller = new AbortController();
  const timeoutId = window.setTimeout(() => {
    // Give a helpful error message instead of "signal is aborted without reason".
    controller.abort(new DOMException("Supabase request timed out", "TimeoutError"));
  }, timeoutMs);

  try {
    return await fetch(input, { ...init, signal: controller.signal });
  } catch (e) {
    const msg = String((e as any)?.message ?? "");
    if (controller.signal.aborted) {
      console.warn("[supabase] request timed out", { url, timeoutMs, message: msg });
    }
    throw e;
  } finally {
    window.clearTimeout(timeoutId);
  }
};

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: fetchWithTimeout,
  },
});