// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://pvrqcuinoerspbdflxiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2cnFjdWlub2Vyc3BiZGZseGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwNjMwNzksImV4cCI6MjA4MDYzOTA3OX0.2Nf3nXm1KpXEUVmH4XfWT7N90-CTGTZPtbqfSh0ZcBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const REST_TIMEOUT_MS = 20_000;
// Auth can involve DB work (rate limits, password hashing, etc.). Allow a longer window than REST reads.
const AUTH_TIMEOUT_MS = 45_000;

const createTimeoutSignal = (ms: number, label: string) => {
  const controller = new AbortController();
  const timeoutId = window.setTimeout(() => {
    controller.abort(new DOMException(`${label} timed out`, "TimeoutError"));
  }, ms);
  return {
    signal: controller.signal,
    cancel: () => window.clearTimeout(timeoutId),
  };
};

const fetchWithTimeout: typeof fetch = async (input, init) => {
  const url = typeof input === "string" ? input : (input as Request).url;
  const timeoutMs = url.includes("/auth/v1") ? AUTH_TIMEOUT_MS : REST_TIMEOUT_MS;

  const timeout = createTimeoutSignal(timeoutMs, "Supabase request");

  // Always enforce our timeout, even if the caller provided a signal.
  const controller = new AbortController();
  const onAbort = () => {
    controller.abort();
  };

  if (init?.signal) {
    if (init.signal.aborted) controller.abort();
    else init.signal.addEventListener("abort", onAbort, { once: true });
  }
  if (timeout.signal.aborted) controller.abort();
  else timeout.signal.addEventListener("abort", onAbort, { once: true });

  try {
    return await fetch(input, { ...init, signal: controller.signal });
  } catch (e) {
    const msg = String((e as any)?.message ?? "");
    if (timeout.signal.aborted) {
      console.warn("[supabase] request timed out", { url, timeoutMs, message: msg });
    }
    throw e;
  } finally {
    timeout.cancel();
    if (init?.signal) init.signal.removeEventListener("abort", onAbort);
    timeout.signal.removeEventListener("abort", onAbort);
  }
};

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: fetchWithTimeout,
  },
});