// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://pvrqcuinoerspbdflxiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2cnFjdWlub2Vyc3BiZGZseGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwNjMwNzksImV4cCI6MjA4MDYzOTA3OX0.2Nf3nXm1KpXEUVmH4XfWT7N90-CTGTZPtbqfSh0ZcBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const DEFAULT_TIMEOUT_MS = 10_000;

const fetchWithTimeout: typeof fetch = async (input, init) => {
  // If a signal is already provided, respect it.
  if (init?.signal) return fetch(input, init);

  const controller = new AbortController();
  const timeoutId = window.setTimeout(() => controller.abort(), DEFAULT_TIMEOUT_MS);

  try {
    return await fetch(input, { ...init, signal: controller.signal });
  } finally {
    window.clearTimeout(timeoutId);
  }
};

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: fetchWithTimeout,
  },
});